### ISSUE TITLE
Add hover effect to activity titles.

### ISSUE THREAD

**Issue by chrisfried** [chrisfried/guardian-theater-ng2#12]

**Comment by jbccollins** [comment]
This seems like something that a newbie to this project could pick up. @chrisfried are there any design details you'd like to see for this?

**Comment by chrisfried** [comment]
I can make some up. If you hover over a player name or an offsite link, the background color changes to show you it's a link. At present, this does not happen when hovering over the activity title or the spinner/x/count box, both of which link to the activity. So...

- Hovering over either the activity title or the the count/spinner block should apply a hover state to both elements.
- The class should have CSS animations to match the fade in of existing hover states.
- I've been making the hover states about 3 steps darker for each channel. i.e. #666 becomes #333. This could probably be done with some fancy Sass, I've just manually entered values thus far.
- Keep in mind there are several different starting background colors dependent on the activity type.

**Comment by jbccollins** [comment]
Ok cool. What are your thoughts on introducing a SASS partials file to store variables and mixins? Does something like https://github.com/jbccollins/guardian-theater-ng2/commit/cf5e43217971d4037ec495f0b1e9f0eddfe347dd
interest you at all or would you prefer to stick with raw hex/rgb stuff?

**Comment by jbccollins** [comment]
Pinging @chrisfried .

**Comment by chrisfried** [comment]
Ah. There's a handy draft in my email I thought I'd sent in reply to your comment:

Sounds good to me! I set them up as Sass files so cool Sass features could be used.

The style files are a bit of a mess. I was pulling over styles from v1 and grafting on new styles as I went without much planning. There's some replication across components that could be made DRYer.
