### ISSUE TITLE
Add onclick play/pause functionality to clips

### ISSUE THREAD

**Issue by jbccollins** [chrisfried/guardian-theater-ng2#14]
Right now only twitch clips will play when you click on the thumbnail because of https://github.com/chrisfried/guardian-theater-ng2/blob/master/src/app/activity/activity.component.html#L128

add something similar to the video tag for the xbox clips.

**Comment by jbccollins** [comment]
@chrisfried I'd be up for doing this if you're ok with that

**Comment by chrisfried** [comment]
There's actually supposed to be a big ol' play button on the thumbnail that can start clips. I see it appear correctly every now and again, haven't taken the time to figure out what's up with it.

You're most welcome to put together a pull request!

**Comment by jbccollins** [comment]
Cool! Ok what's your process here? Do you want a new branch for this issue? It doesn't seem like anyone has permission to create a new branch other than you.

**Comment by chrisfried** [comment]
There isn't much of a process yet. Make a fork, make your changes there (in master or a branch, doesn't matter to me), and submit a pull request.
